### ISSUE TITLE
Broken README image

### ISSUE THREAD

**Issue by arezzg** [PowerMan2206/archstall#12]
# Would you look at that
![image](https://github.com/user-attachments/assets/3660e242-70ad-407f-9222-7d62849d703f)

The image is broken! We need to find breadtard's dad in /var

I suggest having another talk with her to redo this conversation, or just rescreenshot the chat

**Comment by PowerMan2206** [comment]
I'm gonna push an update soon where I drop BIOS support (because who uses BIOS) and switch from GRUB to rEFInd. Gonna fix this in that one.

**Comment by arezzg** [comment]
Appreciate the swift response time but wait what the hell? rEFInd? what's wrong with systemd-boot or GRUB?

**Comment by PowerMan2206** [comment]
Idk it looks nice

Also @WessellUrdata demands anything that's not GRUB and he has my family hostage so I have to comply with his demands.

**Comment by arezzg** [comment]
The first reason is acceptable.

@WessellUrdata  I will find you and I will --no-preserve-root your ass
